# Generated by Django 3.1.8 on 2021-05-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
