# Generated by Django 3.1.8 on 2021-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_delete_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('balance', models.FloatField(db_column='BALANCE', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Variable',
                'db_table': 'Variable',
                'managed': True,
            },
        ),
    ]
